### ISSUE TITLE
关于.h5文件的生成

### ISSUE THREAD

**Issue by Young-Zzz** [hellloxiaotian/ACNet#4]
田教授您好：
  请问在ACNet训练时，生成训练集h5文件的代码可以参考哪种方法呢？有具体的程序吗
谢谢！

**Comment by Young-Zzz** [comment]
抱歉，我没有注意到，现在看到了

**Comment by hellloxiaotian** [comment]
好的！


祝好！
田春伟 副教授
西北工业大学
















在 2022-06-20 20:13:56，"User-Xzm" ***@***.***> 写道：

抱歉，我没有注意到，现在看到了

**Comment by Young-Zzz** [comment]
田教授您好，请问如何训练ACNet呢，train.py所用到的solver.fit()中，train的指标结果都是0，所以我现在想要找出这个问题
line98：if cfg.verbose and self.step % cfg.print_interval == 0:
这个设置为0的话，代码判定为1，没有计算下面的psnr，而是返回到71行，while True语句，请问这里为什么设置成0呢？


line100：psnr&nbsp;=&nbsp;self.evaluate("dataset/Urban100",&nbsp;scale=cfg.scale,&nbsp;num_step=self.step)
这里我修改目录"dataset/Urban100"为DIV2K.h5文件所在地址还是DIV2K整个目录，指标结果还是PSNR=0，SSIM=0





line114：def evaluate(self, test_data_dir, scale=4, num_step=0):
这里为什么定义的是test_data_dir，包括Line122-126,因为我生成DIV2K.h5文件后，train结果PSNR\SSIM都是0，






以上三个问题是在train.py中所遇到的，还请您不吝赐教


或者可以




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "hellloxiaotian/ACNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月20日(星期一) 晚上11:52
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [hellloxiaotian/ACNet] 关于.h5文件的生成 (Issue #4)





 好的！
 
 
 祝好！
 田春伟 副教授
 西北工业大学
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 在 2022-06-20 20:13:56，"User-Xzm" ***@***.***&gt; 写道：
 
 抱歉，我没有注意到，现在看到了

**Comment by hellloxiaotian** [comment]
你好：


   训练代码中的测试部分是方便观察训练去噪模型过程中性能好坏，模型是否稳定等。
   训练过程中的PSNR=0，可能是数据的路径搞错，导致读取数据没有成功~


祝好！
春伟 


















在 2022-06-21 21:51:59，"User-Xzm" ***@***.***> 写道：

田教授您好，请问如何训练ACNet呢，train.py所用到的solver.fit()中，
line114：def evaluate(self, test_data_dir, scale=4, num_step=0):
这里为什么定义的是test_data_dir，包括Line122-126,因为我生成DIV2K.h5文件后，train结果PSNR\SSIM都是0，所以我现在想要找出这个问题
line100：psnr = self.evaluate("dataset/Urban100", scale=cfg.scale, num_step=self.step)
这里我修改目录为DIV2K.h5文件所在地址，但是还是PSNR=0


以上两个问题是在train.py中所遇到的，还请您不吝赐教




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "hellloxiaotian/ACNet" ***@***.***&gt;;
发送时间:&nbsp;2022年6月20日(星期一) 晚上11:52
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [hellloxiaotian/ACNet] 关于.h5文件的生成 (Issue #4)





好的！


祝好！
田春伟 副教授
西北工业大学
















在 2022-06-20 20:13:56，"User-Xzm" ***@***.***&gt; 写道：

抱歉，我没有注意到，现在看到了
